Style/Encoding:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/ParallelAssignment:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
  Max: 35

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120
